//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSIRails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class infosarret
    {
        public int idarret { get; set; }
        public int idvoyage { get; set; }
        public int idgare { get; set; }
        public Nullable<System.TimeSpan> heureArrive { get; set; }
        public Nullable<System.TimeSpan> heureDepart { get; set; }
    
        public virtual gare gare { get; set; }
        public virtual voyage voyage { get; set; }
    }
}
