//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSIRails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voyage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public voyage()
        {
            this.infosarrets = new HashSet<infosarret>();
            this.retards = new HashSet<retard>();
        }
    
        public int idvoyage { get; set; }
        public Nullable<int> GareDepart { get; set; }
        public Nullable<int> gareArrive { get; set; }
        public Nullable<System.DateTime> dateDepart { get; set; }
        public Nullable<System.DateTime> dateArrive { get; set; }
        public Nullable<System.TimeSpan> HeureDepart { get; set; }
        public Nullable<System.TimeSpan> heureArrive { get; set; }
        public Nullable<int> idtrain { get; set; }
    
        public virtual gare gare { get; set; }
        public virtual gare gare1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infosarret> infosarrets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<retard> retards { get; set; }
        public virtual train train { get; set; }
    }
}
